version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - 6379:6379
  insight:
    image: redislabs/redisinsight
    ports:
      - 8001:8001
  mongo:
    image: mongo:5
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081