version: '3.8'
services:
  zookeeper:
    image: zookeeper:3.8
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
      - "8888:8888"
  consul:
    image: hashicorp/consul:1.13
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
