package java8;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.RepeatedTest;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import java.util.HashMap;
import java.util.Map;

import static java.lang.Integer.MAX_VALUE;
import static org.junit.jupiter.api.Assertions.*;

public class RandomGeneratorTest {

    RandomGenerator randomGenerator;

    @BeforeEach
    void setup() {
        randomGenerator = new RandomGenerator();
        numberCounts = new HashMap<>();

    }

    @Test
    @DisplayName("Check that generated random value is less than upper bound")
        //Given-when-then
    void generate_invokeWithValidBound_resultIsLess() {
        //void generatedNumberShouldBeSmallerThanMax() {
        int max = 50;
        int result = randomGenerator.generate(max);
        assertTrue(result < max);
    }

    @DisplayName("Test that checks if returned type is an int")
    @Test
    void returnsInt() {
        int ans = randomGenerator.generate(1); //always returns 0
        assertEquals(0, ans); // checking if returned type is an int
    }

    @Test
    public void testIllegalArgumentException() {

        assertThrows(IllegalArgumentException.class,
                () -> randomGenerator.generate(-5));
    }

    @RepeatedTest(1_000_000)
    void shouldReturnNumbersSmallerThanMaxValue() {
        assertTrue(randomGenerator.generate(MAX_VALUE) < MAX_VALUE);
    }

    @Test
    @DisplayName("Check if number is random")
    void generate_IfTwoNumbersAreNotTheSame() {
        final int max = 1000;
        int numberOne = randomGenerator.generate(max);
        int numberTwo = randomGenerator.generate(max);
        assertNotEquals(numberOne, numberTwo);
    }


    private Map<Integer, Integer> numberCounts;

    @RepeatedTest(value = 100)
    @DisplayName("Test that generates samples * max - the upper border of random numbers - numbers and checks if the numbers are random")
    public void checkIfNumbersAreRandom() {
        int samples = 10000;  //how many samples we wont for each number (+ / - deviation)
        int max = 10;   // max int for rangdom generator
        double deviation = 0.04; //deviation - minimal estimated range in which we can assume that number repeats randomly


        for (int i = 0; i < max * samples; i++) {  //making max (here 10) times samples (here 1000) iteration to generate max time samples numbers.

            int number = randomGenerator.generate(max);  //getting number from the method of RandomGenerator
            if (numberCounts.isEmpty()) { //if Map od counts is empty, adding number with 1st count (variable number is key)
                numberCounts.put(number, 1);

            } else if (!numberCounts.containsKey(number)) { //if there is not such number (key) in Map - add one and give it 1 count
                numberCounts.put(number, 1);

            } else {
                numberCounts.put(number, (numberCounts.get(number) + 1)); //if there is a number (key) in Map increment it value
            }
        }

        int lowerBand = (int) Math.floor((double) samples * (1.0 - deviation)); //establishing deviation range - bottom and upper
        int upperBand = (int) Math.floor((double) samples * (1.0 + deviation));

        for (int key : numberCounts.keySet()) { //testing if counts of numbers generated by random generator are in estimated bands for randomness

            assertTrue(numberCounts.get(key) >= lowerBand, "Counts of" + numberCounts.get(key) + "number: " + key + "are not >= than lower band: " + lowerBand);
            assertTrue(numberCounts.get(key) <= upperBand, "Counts of" + numberCounts.get(key) + "number: " + key + "are not <= than upper bank: " + upperBand);

        }
    }

    @ParameterizedTest
    @ValueSource(ints = {-2, Integer.MIN_VALUE, 0})
    @DisplayName("Test that IllegalArgumentException is thrown when invalid number is passed as max")
    void generate_invalidUpperBound_exceptionThrown(int upperBound) {
        assertThrows(IllegalArgumentException.class, () -> {
            randomGenerator.generate(upperBound);
        });
    }

    @Test
    @DisplayName("Test that IllegalArgumentException is thrown when negative number is passed as max")
    void generator_negativeNumber_resultIsIllegalArgumentException() {
        assertThrows(IllegalArgumentException.class, () -> {
            randomGenerator.generate(-2);
        });
    }

    @Test
    @DisplayName("Test that IllegalArgumentException is thrown when large negative number is passed as max")
    void generator_largeNegativeNumber_resultIsIllegalArgumentException() {
        assertThrows(IllegalArgumentException.class, () -> {
            randomGenerator.generate(Integer.MIN_VALUE);
        });
    }

    @Test
    @DisplayName("Test that IllegalArgumentException is thrown when zero is passed as max")
    void generator_zero_resultIsIllegalArgumentException() {
        assertThrows(IllegalArgumentException.class, () -> {
            randomGenerator.generate(0);
        });
    }

    @Test
    @DisplayName("Test that generator returns integer value")
    void generator_resultIsInteger() {
        assertTrue(Integer.class.isInstance(randomGenerator.generate(100)));
    }

    @Test
    @DisplayName("Test that values returned by generator are random (distributed uniformly)")
    void generator_uniformDistributionTest() {
        //I am using "Chi-Squared" statistical hypothesis test
        //It allows me to check, if generated numbers are spread out reasonably
        //For example, when generating  1000 random numbers which values would be in range [0, 100) we would expect to
        //get somewhere around 1000/100 numbers of each value
        //numberOfRands should be at least greater than 10*maxValue
        int maxValue = 50000; //Generating random values in range [0, maxValue)
        int numberOfRands = 999999; //Number of rands generated
        double f = 0;

        int[] frequencies = new int[maxValue]; //How many times each value from [0, maxValue) was drawn

        for (int i = 0; i < numberOfRands; i++) {
            frequencies[randomGenerator.generate(maxValue)]++;
        }

        for (int i = 0; i < maxValue; i++) {
            f += Math.pow(frequencies[i] - ((double) numberOfRands / maxValue), 2); //Calculations due to "Chi-Squared" formula
        }

        assertTrue(Math.abs((f * maxValue / numberOfRands) - maxValue) <= 2 * Math.sqrt(maxValue));
    }

    @RepeatedTest(1_000)
    @DisplayName("Test if amount of generated numbers for each int is within expected bonds")
    void testRandomness() {
        Map<Integer, Integer> numberCount = new HashMap<>();

        //given
        int cases = 10000;
        int highestNumber = 10;
        double deviation = 0.05;
        double maxExpectedResults = (cases / highestNumber) + (cases * deviation);
        double minExpectedResults = (cases / highestNumber) - (cases * deviation);

        for (int i = 0; i < highestNumber; i++) {
            numberCount.put(i, 0);
        }

        //when
        for (int i = 0; i < cases; i++) {
            int generatedInt = randomGenerator.generate(highestNumber);
            numberCount.put(generatedInt, numberCount.get(generatedInt) + 1);
            //numberCount.compute(generatedInt, (key, value) -> value == null ? 1: value + 1);
        }

        //then
        for (int i = 0; i < highestNumber; i++) {
            assertTrue(numberCount.get(i) <= maxExpectedResults);
            assertTrue(numberCount.get(i) >= minExpectedResults);
        }

    }
}
