package java8;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.RepeatedTest;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import java.util.Map;

import static java.lang.Integer.MAX_VALUE;
import static org.junit.jupiter.api.Assertions.*;

public class RandomGeneratorTest {

    RandomGenerator randomGenerator;

    @BeforeEach
    void setup() {
        randomGenerator = new RandomGenerator();
        // numberCounts = new HashMap<Integer, Integer>();

    }

    @Test
    @DisplayName("Check that generated random value is less than upper bound")
        //Given-when-then
    void generate_invokeWithValidBound_resultIsLess() {
        //void generatedNumberShouldBeSmallerThanMax() {
        int max = 50;
        int result = randomGenerator.generate(max);
        assertTrue(result < max);
    }

    @DisplayName("Test that checks if returned type is an int")
    @Test
    void returnsInt() {
        int ans = randomGenerator.generate(1); //always returns 0
        assertEquals(0, ans); // checking if returned type is an int
    }

    @Test
    public void testIllegalArgumentException() {

        assertThrows(IllegalArgumentException.class,
                () -> randomGenerator.generate(-5));
    }

    @RepeatedTest(1_000_000)
    void shouldReturnNumbersSmallerThanMaxValue() {
        assertTrue(randomGenerator.generate(MAX_VALUE) < MAX_VALUE);
    }

    @Test
    @DisplayName("Check if number is random")
    void generate_IfTwoNumbersAreNotTheSame() {
        final int max = 1000;
        int numberOne = randomGenerator.generate(max);
        int numberTwo = randomGenerator.generate(max);
        assertNotEquals(numberOne, numberTwo);
    }


    private Map<Integer, Integer> numberCounts;

    @RepeatedTest(value = 100)
    @DisplayName("Test that generates samples * max - the upper border of random numbers - numbers and checks if the numbers are random")
    public void checkIfNumbersAreRandom() {
        int samples = 10000;  //how many samples we wont for each number (+ / - deviation)
        int max = 10;   // max int for rangdom generator
        double deviation = 0.04; //deviation - minimal estimated range in which we can assume that number repeats randomly


        for (int i = 0; i < max * samples; i++) {  //making max (here 10) times samples (here 1000) iteration to generate max time samples numbers.

            int number = randomGenerator.generate(max);  //getting number from the method of RandomGenerator
            if (numberCounts.isEmpty()) { //if Map od counts is empty, adding number with 1st count (variable number is key)
                numberCounts.put(number, 1);

            } else if (!numberCounts.containsKey(number)) { //if there is not such number (key) in Map - add one and give it 1 count
                numberCounts.put(number, 1);

            } else {
                numberCounts.put(number, (numberCounts.get(number) + 1)); //if there is a number (key) in Map increment it value
            }
        }

        int lowerBand = (int) Math.floor((double) samples * (1.0 - deviation)); //establishing deviation range - bottom and upper
        int upperBand = (int) Math.floor((double) samples * (1.0 + deviation));

        for (int key : numberCounts.keySet()) { //testing if counts of numbers generated by random generator are in estimated bands for randomness

            assertTrue(numberCounts.get(key) >= lowerBand, "Counts of" + numberCounts.get(key) + "number: " + key + "are not >= than lower band: " + lowerBand);
            assertTrue(numberCounts.get(key) <= upperBand, "Counts of" + numberCounts.get(key) + "number: " + key + "are not <= than upper bank: " + upperBand);

        }
    }

    @ParameterizedTest
    @ValueSource(ints = {-2, Integer.MIN_VALUE, 0})
    @DisplayName("Test that IllegalArgumentException is thrown when invalid number is passed as max")
    void generate_invalidUpperBound_exceptionThrown(int upperBound) {
        assertThrows(IllegalArgumentException.class, () -> {
            randomGenerator.generate(upperBound);
        });
    }

    @Test
    @DisplayName("Test that IllegalArgumentException is thrown when negative number is passed as max")
    void generator_negativeNumber_resultIsIllegalArgumentException() {
        assertThrows(IllegalArgumentException.class, () -> {
            randomGenerator.generate(-2);
        });
    }

    @Test
    @DisplayName("Test that IllegalArgumentException is thrown when large negative number is passed as max")
    void generator_largeNegativeNumber_resultIsIllegalArgumentException() {
        assertThrows(IllegalArgumentException.class, () -> {
            randomGenerator.generate(Integer.MIN_VALUE);
        });
    }

    @Test
    @DisplayName("Test that IllegalArgumentException is thrown when zero is passed as max")
    void generator_zero_resultIsIllegalArgumentException() {
        assertThrows(IllegalArgumentException.class, () -> {
            randomGenerator.generate(0);
        });
    }

    @Test
    @DisplayName("Test that generator returns integer value")
    void generator_resultIsInteger() {
        assertTrue(Integer.class.isInstance(randomGenerator.generate(100)));
    }
}
